version: '3.3'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=homestead
      - MARIADB_DATABASE=homestead
      - MARIADB_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
       - db_data:/var/lib/mysql

  laravel:
    tty: true
    image: 'bitnami/laravel:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=homestead
      - DB_DATABASE=homestead
      - DB_PASSWORD=secret
    depends_on:
      - mariadb
      - redis
    ports:
      - 3000:3000
    volumes:
      - ./:/app

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:  
  db_data:
